# Generated by Django 3.0.7 on 2020-06-11 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('dates', models.TextField(blank=True, null=True)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campaign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('pc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('class_level', models.SmallIntegerField(blank=True, null=True)),
                ('strength', models.SmallIntegerField(blank=True, null=True)),
                ('dexterity', models.SmallIntegerField(blank=True, null=True)),
                ('constitution', models.SmallIntegerField(blank=True, null=True)),
                ('intelligence', models.SmallIntegerField(blank=True, null=True)),
                ('wisdom', models.SmallIntegerField(blank=True, null=True)),
                ('charisma', models.SmallIntegerField(blank=True, null=True)),
                ('armor_class', models.SmallIntegerField(blank=True, null=True)),
                ('initiative', models.SmallIntegerField(blank=True, null=True)),
                ('hp', models.SmallIntegerField(blank=True, null=True)),
                ('xp', models.SmallIntegerField(blank=True, null=True)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('spells', models.TextField(blank=True, null=True)),
                ('treasure', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PcClass',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pc_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('discord_id', models.TextField(blank=True, null=True)),
                ('zoom_id', models.TextField(blank=True, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'race',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonCampaign',
            fields=[
                ('is_dm', models.BooleanField(blank=True, null=True)),
                ('campaign_id_campaign', models.OneToOneField(db_column='campaign_id_campaign', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manager.Campaign')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person_campaign',
                'managed': False,
            },
        ),
    ]
