# Generated by Django 3.0.7 on 2020-06-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personcampaign',
            options={},
        ),
    ]
