# Generated by Django 3.0.7 on 2020-06-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200615_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personcampaign',
            options={'managed': False},
        ),
    ]
