# Generated by Django 3.0.7 on 2020-06-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200615_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personcampaign',
            options={'managed': True},
        ),
    ]
