# Generated by Django 3.0.7 on 2020-06-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200611_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False},
        ),
    ]
