# Generated by Django 3.0.7 on 2020-06-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200615_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcampaign',
            name='person_campaign_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        # Our Postgres database tables already have these so we'll just comment them out:

        # migrations.AddField(
        #     model_name='personcampaign',
        #     name='user_id_person',
        #     field=models.ForeignKey(db_column='user_id_person', on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Person'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='personcampaign',
        #     name='campaign_id_campaign',
        #     field=models.ForeignKey(db_column='campaign_id_campaign', on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Campaign'),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='personcampaign',
        #     unique_together={('campaign_id_campaign', 'user_id_person')},
        # ),
    ]
