# Generated by Django 3.0.7 on 2020-06-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200615_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pc',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='personcampaign',
            options={'managed': False},
        ),
    ]
