# Generated by Django 3.0.7 on 2020-06-22 21:51

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20200622_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='campaign_id_campaign',
            field=models.ForeignKey(blank=True, db_column='campaign_id_campaign', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Campaign'),
        ),

    ]
