# Generated by Django 3.0.7 on 2020-06-22 21:59

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20200622_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='id_alignment',
            field=models.ForeignKey(db_column='id_alignment', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Alignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pc',
            name='id_pc_class',
            field=models.ForeignKey(db_column='id_pc_class', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.PcClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pc',
            name='id_race',
            field=models.ForeignKey(db_column='id_race', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Race'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pc',
            name='user_id_person',
            field=models.ForeignKey(blank=True, db_column='user_id_person', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Person'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='dates',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='pc_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
