# Generated by Django 3.0.7 on 2020-06-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20200611_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False},
        ),
    ]
